using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Security.Cryptography;

namespace Lifes
{
    public enum Gas
    {
        nitrogen,
        oxygen,
        argon,
        carbon_dioxide,
        water
    }
    public enum TerrainType
    {
        Water,
        Plain,
        Forest,
        Mountain
    }
    public class World
    {
        public int Width, Height;
        public string seed { get; set; }
        public static TerrainType[,] TerrainMap { get; private set; }
        public int Octaves { get; set; } = 4;
        public float Persistence { get; set; } = 0.5f;
        public float Lacunarity { get; set; } = 2.0f;
        public Environment Environment;

        private Perlin perlin;
        private static Random Random = new Random();

        public static string GenerateRandomString(int length)
        {
            const string chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string([.. Enumerable.Repeat(chars, length).Select(s => s[Random.Next(s.Length)])]);
        }

        public void CreateWorld(string seed = "", int width = 100, int height = 100)
        {
            Width = width;
            Height = height;

            this.seed = seed;
        }
        public static TerrainType GetNowBiome()
        {
            return TerrainType.Water;
        }
        public void GenerateWorld(float scale = 0.05f)
        {
            Console.WriteLine($"Generated by : {seed}");
            // 文字列シード → 数値化
            int numericSeed = Hash(seed);
            perlin = new Perlin(numericSeed);

            TerrainMap = new TerrainType[Width, Height];

            for (int x = 0; x < Width; x++)
            {
                for (int y = 0; y < Height; y++)
                {
                    float totalNoise = 0;
                    float amplitude = 1.0f;
                    float frequency = scale;
                    float maxAmplitude = 0;

                    for (int i = 0; i < Octaves; i++)
                    {
                        float noiseValue = perlin.Noise(x * frequency, y * frequency);
                        totalNoise += (noiseValue - 0.5f) * amplitude;
                        maxAmplitude += amplitude;

                        amplitude *= Persistence;
                        frequency *= Lacunarity;
                    }

                    float normalizedNoise = (totalNoise / maxAmplitude) + 0.5f;

                    if (normalizedNoise < 0.45f)
                        TerrainMap[x, y] = TerrainType.Water;
                    else if (normalizedNoise < 0.6f)
                        TerrainMap[x, y] = TerrainType.Plain;
                    else if (normalizedNoise < 0.7f)
                        TerrainMap[x, y] = TerrainType.Forest;
                    else
                        TerrainMap[x, y] = TerrainType.Mountain;
                }
            }
        }

        public static int Hash(string seed)
        {
            using var sha = SHA256.Create();
            byte[] hash = sha.ComputeHash(Encoding.UTF8.GetBytes(seed));
            return BitConverter.ToInt32(hash, 0);
        }

        public TerrainType GetTerrain(int x, int y)
        {
            if (x < 0 || y < 0 || x >= Width || y >= Height)
                throw new ArgumentOutOfRangeException();
            return TerrainMap[x, y];
        }
    }
}
